# Generated by Django 4.0.5 on 2022-06-24 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RackModel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'rack',
            },
        ),
        migrations.CreateModel(
            name='LogisticModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfid_tag', models.CharField(max_length=16, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.rackmodel')),
            ],
            options={
                'db_table': 'logistic',
            },
        ),
    ]
