# Generated by Django 4.0.5 on 2022-06-22 10:43

from django.db import migrations

from apismatic.user.models.role_model import Role


def seed_roles(apps, schema_editor):
    Role.objects.create(id=Role.LOGISTIC_OWNER_ID, name=Role.LOGISTIC_OWNER_NAME)
    Role.objects.create(id=Role.WAREHOUSE_EMPLOYEE_ID, name=Role.WAREHOUSE_EMPLOYEE_NAME)
    Role.objects.create(id=Role.WAREHOUSE_OWNER_ID, name=Role.WAREHOUSE_OWNER_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_roles)
    ]
