# Generated by Django 4.0.5 on 2022-06-23 06:34

from django.db import migrations
from apismatic.user.models.user_model import User


def seed_warehouse_owner(apps, schema_editor):
    User.objects.create_warehouse_owner(
        name='ADMIN',
        email='admin@smatic.com',
        password='Password1234!',
        phone=0,
        address='Yogyakarta')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220622_1043'),
    ]

    operations = [
        migrations.RunPython(seed_warehouse_owner)
    ]
